# Generated by Django 2.2.12 on 2020-05-26 08:20
import os
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone
from django.contrib.auth import get_user_model


class Migration(migrations.Migration):

    def create_superuser(apps, schema_editor):
        superuser = get_user_model()(
            is_active=True,
            is_superuser=True,
            is_staff=True,
            username=os.environ['ADMIN_USERNAME'],
            email=os.environ['ADMIN_EMAIL'],
            last_login=timezone.now(),
            user_type=5,
        )
        superuser.set_password(os.environ['ADMIN_PASSWORD'])
        superuser.save()

    dependencies = [
        ('users', '0001_initial')
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]
