# Generated by Django 2.2.12 on 2020-05-26 08:20
import os
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone
from django.contrib.auth import get_user_model


class Migration(migrations.Migration):

    def create_superuser(apps, schema_editor):
        superuser = get_user_model()(
            is_active=True,
            is_superuser=True,
            is_staff=True,
            username=os.environ['ADMIN_USERNAME'],
            email=os.environ['ADMIN_EMAIL'],
            last_login=timezone.now(),
        )
        superuser.set_password(os.environ['ADMIN_PASSWORD'])
        superuser.save()

    def create_testusers(apps, schema_editor):
        testuser1 = get_user_model()(
            username="tester1", 
            email="tester1@example.com", 
            password="Pass12345"
        )
        testuser1.save()

        testuser2 = get_user_model()(
            username="tester2", 
            email="tester2@example.com", 
            password="Pass12345"
        )
        testuser2.save()

    dependencies = [
        ('users', '0001_initial')
    ]

    operations = [
        migrations.RunPython(create_testusers),
        migrations.RunPython(create_superuser),
    ]
