version: '3'
services:

  db:
    container_name: postgres_container
    image: postgres:12
    environment:
      - DB_NAME=${DB_NAME}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - qlma_network
    restart: unless-stopped

  web:
    container_name: web_container
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - FACILITY_NAME=${FACILITY_NAME}
      - FACILITY_ADDRESS=${FACILITY_ADDRESS}
      - FACILITY_EMAIL=${FACILITY_EMAIL}
      - FACILITY_PHONE=${FACILITY_PHONE}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - SMTP_EMAIL_USER=${SMTP_EMAIL_USER}
      - SMTP_EMAIL_PASS=${SMTP_EMAIL_PASS}
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db:db
      - chrome:chrome
      - firefox:firefox 
    networks:
      - qlma_network
    restart: unless-stopped

  pgadmin:
    hostname: pgadmin4
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
       - pgadmin_data:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - qlma_network
    restart: unless-stopped

    
  #https://github.com/SeleniumHQ/docker-selenium/blob/trunk/docker-compose-v3.yml
  selenium-hub:
    container_name: selenium-hub
    image: selenium/hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    networks:
      - qlma_network

  chrome:
    image: selenium/node-chrome-debug
    container_name: chrome
    volumes:
    #  - ./selenium_server_deploy.jar:/opt/selenium/selenium-server.jar
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      #- REMOTE_HOST="http://selenium-hub:4444"
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444
    #environment:
      #- HUB_HOST=selenium-hub
      #- HUB_HOST=localhost
      #- HUB_PORT=4444
    ports:
      - "6900:5900"
    networks:
      - qlma_network

  firefox:
    image: selenium/node-firefox-debug
    container_name: firefox
    volumes:
    #  - ./selenium_server_deploy.jar:/opt/selenium/selenium-server.jar
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      #- REMOTE_HOST="http://selenium-hub:4444"
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444
    #environment:
      #- HUB_HOST=selenium-hub
      #- HUB_HOST=localhost
      #- HUB_PORT=4444
    ports:
      - "6901:5900"
    networks:
      - qlma_network

networks:
  qlma_network:

volumes:
    postgres_data:
    pgadmin_data: