version: '3'

services:

  db:
    container_name: postgres_container
    image: postgres:12
    environment:
      - DB_NAME=${DB_NAME}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres
    restart: unless-stopped

  web:
    container_name: web_container
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - FACILITY_NAME=${FACILITY_NAME}
      - FACILITY_LOCATION=${FACILITY_LOCATION}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - SMTP_EMAIL_USER=${SMTP_EMAIL_USER}
      - SMTP_EMAIL_PASS=${SMTP_EMAIL_PASS}
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db:db
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    hostname: pgadmin4
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
       - pgadmin_data:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:

volumes:
    postgres_data:
    pgadmin_data: