# Generated by Django 3.2 on 2021-04-14 22:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0002_remove_lunch_staff_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lunch',
            name='title',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
