# Generated by Django 3.2 on 2021-05-16 21:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_message_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date_archived',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
